### ISSUE TITLE
Header & Footer - fallback to PNG if browser does not support SVG

### ISSUE THREAD

**Issue by katikaa** [bbc/psammead#383]
**Is your feature request related to a problem? Please describe.**
From what we've seen here, there are browsers that do not support SVGs https://caniuse.com/#search=svg. However these are very low in the stats

**Describe the solution you'd like**
Therefore we would like to fall back to text link (BBC News) working with UX to ensure that the experience is OK

**Comment by jamesbhobbs** [comment]
@jblaut has this been considered as part of ws v1?

**Comment by j-pendlebury** [comment]
@benjaminhobbs we had a conversation about this, however I believe it was decided that this is not a must have for v1. I will bring it up at stand up tomorrow to make sure

**Comment by WeimingFan** [comment]
https://www.dropbox.com/sh/2zyaij3y4r413qu/AABs3DhXbPgULPhMse_c3qUXa?dl=0
I have saved the PNG files in the linked folder here.

**Comment by Bopchy** [comment]
Since most browsers currently support SVG, is this still required?

**Comment by jimjohnsonrollings** [comment]
https://confluence.dev.bbc.co.uk/display/news/July+2019+-+Agreed+browser+support+for+Simorgh

**Comment by clareevansbbc** [comment]
Confirmed this is not a requirement as:
- we never supported this on PAL
- the user stats from last year are low, and are likely even lower now
- the browsers we would be worrying about are not on our supported list (Jim's link above)
